### ISSUE TITLE
Create Pseudo routes in API (login)

### ISSUE THREAD

**Issue by scriptnull** [wordist/wordist.xyz#17]
Psuedo routes are the routes that are not part of REST convention.
- POST /v1/login { username , password }

**Comment by argonlaser** [comment]
What is the need for deviating from REST conventions? Hows does it benefit? @scriptnull

**Comment by scriptnull** [comment]
@argonlaser , I need to study more on this. Will do this as temporary fix for now.

**Comment by scriptnull** [comment]
Done and deployed.
