### ISSUE TITLE
Prototype Word adding page

### ISSUE THREAD

**Issue by scriptnull** [wordist/wordist.xyz#19]
We need a page, where user adds words and meanings + any other fields that is suggested on this issue.

We have to make a prototype of that page , like we did for login + register.

**Comment by scriptnull** [comment]
@killerveee Other UI issues are blocked on API. Until, we unblock it , you could work on this.

**Comment by killerveee** [comment]
## My initial idea of this page :
- We are having a text box at the top of the page with a button. When the word is entered and the button is clicked the page scrolls down to add the details, understanding and examples of that particular word.
  
  ### THING TO BE NOTED
- It would be good if we can get what type of words the user enters, for example not every word is a verb in that manner we have to only show the options available for the words entered by the users. *
- I think usage of labels or tags will be helpful i.e. the user learns the words from some source then enters into our app so he/she will have to choose the labels like verb, adjective, etc

**Comment by killerveee** [comment]
currently working on this #19 word adding page

**Comment by killerveee** [comment]
closing #19 (add-words page done)
