### ISSUE TITLE
Local workflow for frontend app

### ISSUE THREAD

**Issue by scriptnull** [wordist/wordist.xyz#6]
We need to have the frontend app served by a HTTP server. 
#### Goal

If give this command

``` bash
npm start
```

I should be able to see the login/register page in my browser via "localhost:8081"
#### Steps
- Do `npm init` and fill up the details.
- Move the current assets ( js , css and  html ) into public folder
- Serve the pages via express or hapi.js server ( express -e => execute command to initiate express project in case of you are using express to host your pages )

Additional reference : 
https://expressjs.com/en/starter/static-files.html

**Comment by killerveee** [comment]
Closing issue #6

**Comment by killerveee** [comment]
issue #6 closed once and for all.
