### ISSUE TITLE
Could you guys update ReadMe file regarding the goal of this contribution so that the people watching it can follow??

### ISSUE THREAD

**Issue by argonlaser** [wordist/wordist.xyz#7]
@scriptnull

**Comment by scriptnull** [comment]
yes ! Will do it for sure. May be tonight.

**Comment by scriptnull** [comment]
yes. We will be doing this tonight and close this issue after that.

**Comment by argonlaser** [comment]
The goal is to help people add words to the list and help him memorize the words for better vocabulary.
