### ISSUE TITLE
Initialize API as hapi.js project

### ISSUE THREAD

**Issue by scriptnull** [wordist/wordist.xyz#9]

**Comment by argonlaser** [comment]
1. Should we use api repo for this issue?
2. Why move to hapi?

**Comment by scriptnull** [comment]
yes ! we should use api repo.

hapi seems to good and i just wanted experiment a bit with it. So, only we are trying this project with hapi.js

**Comment by scriptnull** [comment]
Basic stuff done here . hence closing.
